USE MASTER;
GO
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'CAN_DB')
BEGIN
    ALTER DATABASE [CAN_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [CAN_DB];
END
GO

CREATE DATABASE CAN_DB ON PRIMARY 
    (   NAME = 'CAN_DB_data', 
        FILENAME = '/var/opt/mssql/data/CAN_DB.mdf', SIZE = 200MB, MAXSIZE = UNLIMITED, FILEGROWTH = 45MB
    ) 
    LOG ON 
    (   NAME = 'CAN_DB_log', 
        FILENAME = '/var/opt/mssql/data/CAN_DB.ldf', SIZE = 150MB, MAXSIZE = 300MB, FILEGROWTH = 45MB
    )
    WITH CATALOG_COLLATION = DATABASE_DEFAULT;
GO
-- activar caractisticas mejoradas en sql server 2022
ALTER DATABASE [CAN_DB] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
    EXEC [CAN_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CAN_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CAN_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CAN_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CAN_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CAN_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CAN_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CAN_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CAN_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CAN_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CAN_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CAN_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CAN_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CAN_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CAN_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CAN_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CAN_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CAN_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CAN_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CAN_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CAN_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CAN_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CAN_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CAN_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [CAN_DB] SET  MULTI_USER 
GO
ALTER DATABASE [CAN_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CAN_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CAN_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CAN_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CAN_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [CAN_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO